<option value="none" selected="selected" label="Select an option"></option>
<option value="windows" label="Microsoft Windows"></option>
<option value="macosx" label="Apple Mac OS X"></option>
<option value="rhel" label="Red Hat Enterprise Linux"></option>
<option value="centos" label="CentOS"></option>
<option value="fedora" label="Fedora"></option>
<option value="scilinux" label="Scientific Linux"></option>
<option value="debian" label="Debian"></option>
<option value="ubuntu" label="Ubuntu"></option>
<option value="biolinux" label="BioLinux"></option>
<option value="slel" label="Suse Enterprise Linux"></option>
<option value="suse" label="OpenSuse"></option>
<option value="gentoo" label="Gentoo"></option>
<option value="mandriva" label="Mandriva"></option>
<option value="arch" label="Arch Linux"></option>
<option value="slackware" label="Slackware"></option>
<option value="otherlinux" label="Other GNU/Linux distribution"></option>
<option value="starbsd" label="FreeBSD/OpenBSD/NetBSD"></option>
<option value="unix" label="HP-UX/AIX/SCO/BSD"></option>
<option value="qnx" label="QNX"></option>
<option value="beos" label="BeOS"></option>
<option value="solaris" label="Solaris"></option>
<option value="other" label="Other operating system"></option>
