#!/bin/bash

# play safe
set -e
set -u

# Standard Debian install

# prepare on hydra and use debproxy for speed

# have dedicated hard-drives for swap and home

# expert install

# hostname: neurodebian
# domain: ''

# all file in one partition

# root: not there
# user: brain
# pwd: neurodebian


# Do a minimal install
# --------------------

# All files in one partition/
# just base system, run selection, but no tasks (not even 'Standard system')

# set root password to 'neurodebian' too
#echo "Set root passwd:"
#passwd root

apt-get install --no-install-recommends -y etckeeper

# setup etckeeper
git config --global user.name NeuroDebian
git config --global user.email nd@localhost

# install new stuff
# -----------------

# Add sources.list for backports and neurodebian
wget -O /etc/apt/sources.list.d/neuro.debian.net.list http://neuro.debian.net/_static/neurodebian.squeeze.us-nh.sources.list

echo "deb http://backports.debian.org/debian-backports squeeze-backports main contrib non-free" > /etc/apt/sources.list.d/backports.debian.org.list
cat << EOT > /etc/apt/preferences.d/backports.debian.org.pref
Package: *
Pin: release a=squeeze-backports
Pin-Priority: 200
EOT

apt-get update -y
# Backports' Release files signed with both ftpmaster and old backports keys
# That causes APT to spit out a warning, but to not confuse users, lets simply
# obtain that key if possible
gpg --keyserver hkp://subkeys.pgp.net --recv-keys 16BA136C && \
        gpg --export 16BA136C | apt-key add - || :

apt-get install -y --allow-unauthenticated neurodebian-keyring
apt-get update -y

# to cheat the VM check
touch /dev/vboxguest
# to get all the stuff in recommends
apt-get install -y dkms neurodebian-guest-additions

apt-get install --no-install-recommends -y \
 gnome-core mc evince bash-completion ntpdate file-roller gnome-utils \
 gnome-themes eog vim \
 software-center gdebi gedit-plugins gnome-media synaptic menu less libxp6

# intermediate cleanup to prevent virtual harddrive from fragmenting too much
find /var/cache/apt/archives/ -name '*.deb' -delete

# cleanup unwanted stuff
# video drivers (all but vesa)
apt-get purge -y $(apt-cache search --names-only --installed xserver-xorg-video | grep xserver-xorg-video | cut -d ' ' -f 1,1) xserver-xorg-video-vesa+
apt-get purge -y brasero

# and whatever is obsolete
apt-get autoremove --purge -y

# custom config
# use NeuroDebian website as default homepage
sed -i -e 's,http://www.debian.org,http://neuro.debian.net,g' /etc/chromium-browser/master_preferences

# reduce grub timeout to speed up boot of VM
sed -i -e 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/g' /etc/default/grub
update-grub

# finally configure geomirror for APT and disable deb-src lists
sed -i -e "s/10.0.0.1:9999/$(dpkg --print-architecture)-geomirror.debian.net/" \
    -e "s/^deb-src/#deb-src/" /etc/apt/sources.list

etckeeper commit "Initial VM setup done"
