#!/bin/bash

family=$1
dist=$2

set -e

if [ -z "$family" ]; then
  echo "You need to provide a distribution family ('debian', 'ubuntu'); prefix with 'nd+' to enable the NeuroDebian repository."
  exit 1
fi

if [ -z "$dist" ]; then
  echo "You need to provide a distribution codename (e.g. 'lenny', 'squeeze')."
  exit 1
fi


. /etc/neurodebian/cmdsettings.sh

# common options
opts="--distribution $dist --debootstrap debootstrap --aptcache $aptcache"

if echo $family | grep -q ubuntu; then
	# Use ubuntu's keyring since otherwise debootstrap would fail
	opts+=" --debootstrapopts --keyring=/usr/share/keyrings/ubuntu-archive-keyring.gpg"
fi

mkdir -p ${cowbuilderroot}/cow

for a in i386 amd64; do
  echo "Building $a base path..."
  cow="${cowbuilderroot}/cow/${family}-${dist}-${a}.cow"
  if [ -d "$cow" ]; then
    echo "${cow} exists. Ignoring arch."
    continue
  fi
  if [ "${family:0:3}" = "nd+" ]; then
  echo "Including NeuroDebian repository..."
    cowbuilder --create --basepath ${cow} $opts \
               --components "$components" \
               --mirror "$mirror" \
               --debootstrapopts --arch=$a \
               --othermirror "deb http://neuro.debian.net/debian $dist main contrib non-free"
    # deploy our key manually since archive with package is not yet
    # available at this point
    mkdir -p ${cow}/etc/apt/trusted.gpg.d
    cp --preserve=mode {,${cow}}/etc/apt/trusted.gpg.d/neurodebian-archive-keyring.gpg
    # Old ubuntus might not have capability to ready from that key yet,
    # so we would need to manually add it
    if [ $dist = 'karmic' ] || [ $dist = 'hardy' ]; then
        chroot ${cow} bash -c "apt-get install -y --force-yes gnupg \
        && /usr/bin/apt-key add /etc/apt/trusted.gpg.d/neurodebian-archive-keyring.gpg \
        && /usr/bin/apt-get update"
    fi
  else
    cowbuilder --create --basepath ${cow} $opts \
               --components "$components" \
               --mirror "$mirror" \
               --debootstrapopts --arch=$a
  fi
done
