#!/bin/bash
#
# Simple frontend for backport-dsc to do it the NeuroDebian way
#

set -e
set -u

release=$1
dscfile=$2

if [ -z "$release" ]; then
  echo "You need to provide a distribution codename (e.g. 'lenny', 'squeeze')."
  exit 1
fi

if [ -z "$2" ]; then
cat << EOT
Script to backport a source package to some target release.

Synopsis
--------

  nd_backport <codename> <dsc file>

EOT
exit 1
fi

# assemble an appropriate backport-dsc call
backport-dsc \
	--maint-name "NeuroDebian Maintainers" \
	--maint-email "team@neuro.debian.net" \
	--target-distribution "$release" \
	--version-suffix "$(nd_querycfg "release backport ids" "$release")" \
	"$dscfile"

# not adding the auto-dep for now
#	--mod-control 's/^Depends:.*$/&, neurodebian-trailer/' \
