#!/bin/bash

set -e
set -u

# Settings/arguments
vendor="NeuroDebian"
vm_version="6.0.0"
vm_arch="amd64"
vm_name="${vendor} ${vm_version} (${vm_arch})"
product_name="${vendor} VirtualMachine (${vm_arch})"
outdir=.

# Common
eula="This virtual appliance contains Free and Open Source Software (FOSS) released under licenses compliant with the Debian Free Software Guidelines (DFSG, see http://www.debian.org/social_contract), such as, GPL, BSD, MIT, etc.  Such software is free to be used or customized for any purpose.

However, by default this virtual machine is also enabled to install additional software from Debian and NeuroDebian repositories that is distributed under more restrictive licenses (e.g. closed-source, non-commercial, research-only). It is the user's responsibility to adhere to the terms and conditions of any particular software that is installed and used in this virtual machine. Copyright and license details for any installed PACKAGE are available in /usr/share/doc/PACKAGE/copyright inside the virtual machine."

out_ovf="${outdir}/${vendor}_${vm_version}_${vm_arch}.ovf"
VBoxManage export "${vm_name}" -o "$out_ovf" \
	--vsys 0 \
	--product "$vm_name" \
	--producturl "http://neuro.debian.net/vm.html" \
	--vendor "${vendor}" \
	--vendorurl "http://neuro.debian.net" \
	--version "$vm_version" \
	--eula "$eula"
