#!/bin/bash

pkg=$1
tdir=$2

# provide deb-src by uncommenting
sed -i -e 's,^#deb-src,deb-src,g' /etc/apt/sources.list

mkdir -p $tdir
cd $tdir
apt-get update
apt-get install -y devscripts dctrl-tools
build-rdeps $pkg >| build-rdeps.output

# Fetch all the sources
grep -v -e '^[-A-Z]' -e '^ *$' build-rdeps.output \
	| tee build-rdeps.list \
	| while read pkg; do
	apt-get source --download-only $pkg
done
