#!/bin/bash

if [ $# -eq 1 ]; then
  family=${1%%-*}
  dist=${1##*-}
elif [ $# -ge 2 ]; then
  family=$1
  dist=$2
fi

set -e

if [ -z "$family" ]; then
  echo "you need to provide a distribution family ('debian', 'ubuntu'); prefix with 'nd+' to enable the neurodebian repository."
  exit 1
fi

if [ -z "$dist" ]; then
  echo "you need to provide a distribution codename (e.g. 'lenny', 'squeeze')."
  exit 1
fi

. /etc/neurodebian/cmdsettings.sh "$family" "$dist"

# common options
opts="--distribution $dist --aptcache $aptcache --buildplace $buildplace"

if [ -n "$3" ]; then
  arch=$3
else
  arch="i386 amd64"
fi

for a in $arch; do
  echo "Updating arch $a..."
  cowbuilder --update --basepath ${cowbuilderroot}/cow/${family}-${dist}-${a}.cow $opts
done
