#!/bin/bash

set -e

# the Debian release to use as a basis for the live-cd
nd_basedist="squeeze"
nd_version="6.0.0"
nd_mirror=

deb_mirror="http://debproxy:9999"

lb config noauto \
  --apt apt \
  --apt-recommends disabled \
  --architecture i386 \
  --archive-areas "main contrib non-free" \
  --binary-images iso-hybrid \
  --binary-indices none \
  --bootstrap-flavour minimal \
  --debian-installer disabled \
  --distribution ${nd_basedist} \
  --hostname neurodebian \
  --iso-application "NeuroDebian Live" \
  --iso-preparer "NeuroDebian v.{nd_version}; http://neuro.debian.net" \
  --iso-publisher "NeuroDebian project; http://neuro.debian.net" \
  --mirror-bootstrap "$mirror/debian/" \
  --mirror-chroot "${deb_mirror}/debian/" \
  --mirror-chroot-security "${deb_mirror}/security/" \
  --security true \
  --username brain \
  --win32-loader enabled \
  ${@}

  # --mirror-bootstrap "http://debian.lcs.mit.edu/debian/" \
  # --packages-lists xfce \

# May be
# Deploy 1:1 copy of the running Live system
# --debian-installer live

# Would be nice to have it utterly useful, but rescue is too bloated, may be
# at least forensics
# --packages-lists

# Do we need any of the additional tools from live.debian.net?
#  --repositories live.debian.net \
